### ISSUE TITLE
request to add piOS bookworm branch (v2)

### ISSUE THREAD

**Issue by theofficialgman** [raspberrypi-ui/wayfire#11]
As previously indicated here https://github.com/raspberrypi-ui/wayfire/issues/10#issue-2232148357 and not responded to, I am requesting that a specific branch be added that contains all patches contained in the current release of the `wayfire` package used in piOS.

As it currently is, the state of the repo has:
1. no wayfire upstream git history https://github.com/WayfireWM/wayfire
2. no branch or even a tag that corresponds to the source code used in releases

These two issues make it difficult for any community member to attempt up-streaming patches or even understand any patches in context. The patchfiles in the dsc are not sufficient to understand the context of the changes.

> You appear to be attempting to prove that I am either mistaken or simply lying about the difficulty of merging our changes with 0.8 and later.

I am not trying to prove either. I have asked repeatedly for `the changes are being shipped in piOS bookworm that include the optimizations (as referred to here https://github.com/raspberrypi-ui/wayfire/issues/8#issuecomment-1951155629) in an appropriate branch`. Having them spread across separate branches with no clear indication of their use does not help your case. Neither does closing an issue as "completed" https://github.com/raspberrypi-ui/wayfire/issues/8 and locking conversations. It also makes building the software and testing any changes (eg: upstream backports) more difficult.

> it might be worth giving me the benefit of the doubt, and assuming that I do actually know what I am talking about...

I could simply trust that you know what your are saying but it would be much much easier for you prove your trustworthiness by just answering the original question which you never did. All you needed to say was something like this:

Hi. We have no intention of merging the changes shipped in piOS bookworm into one branch on this repository. The dsc file contains patch files which apply to the 0.7.5 release of wayfire. The patch files are generated from chosen commits (or groups of commits) across multiple branches. Yes I know this makes it difficult to track changes due to the size of our changes. You can find the specific changes related to the "optimizations" I mentioned in the https://github.com/raspberrypi-ui/wayfire/tree/igalia-bookworm branch which implements our custom "pixman" renderer instead of wayfire's OpenGL renderer.

**Comment by spl237** [comment]
You've now earned yourself a 7 day block from this repo. This will be extended indefinitely if you carry on this deliberate nuisance behaviour.
