### ISSUE TITLE
Drag and drop files between programs?

### ISSUE THREAD

**Issue by Botspot** [raspberrypi-ui/wayfire#5]
Hopefully there is something obvious I am missing here. It seems to work on the official Wayfire because I could not find any open issues about this functionality missing.
On Bookworm, I cannot seem to drag and drop anything between programs. Just today I have documented five separate times when I tried to DnD and nothing happened.
1. Importing a 3D model from pcmanfm to my Cura 3D slicer program.
2. Attaching an image to an email.
3. Adding images to an image editor.
4. Adding music to the VLC playlist.
5. Moving a file from one pcmanfm window to another.

A small note on 4 and 5: If both windows appear side-by-side, I can drag files from one to the other, but if both windows are fullscreen, I an unable to drag the file to the other program icon in the window list on the panel.

It would seem like this would affect anybody using PiOS Bookworm, but a brief search of the RPi Forums does not yield much discussion about this regression. Surely I am not the only user who habitually makes extensive use of drag and drop? It saves so much time and without it, formerly effortless actions become very cumbersome.

**Comment by spl237** [comment]
Drag and drop works fine for me - I have just tested dragging an MP3 file into VLC from the desktop (both the main window and the playlist - both work), dragging an image file from the Pictures folder into the eom image viewer, dragging a text file into Mousepad, dragging a PDF into evince, and dragging files between file manager windows - all work fine with no problems for me. Looks like something wrong on your system somewhere.

**Comment by Botspot** [comment]
I played around with this more. It looks like my Cura slicer does not support Wayland-style dragging, and Chromium was inconsistent in that it worked for one Chrome profile but not the other. I will assume that specific case is my problem to solve.

Dragging between pcmanfm windows does work, but what consistently does *not* work is any type of dragging between maximized windows.
On Bullseye, this is the process for dropping an image into chromium:
1. Locate the file in pcmanfm.
2. Drag the file to Chromium's running program icon in the window list (on the panel), and do not release the file yet.
3. Chromium will raise automatically, and now the file can be dragged to a specific point on the window.

This does not work in any capacity on Bookworm. Dragging files from one maximized program to another, *relying on the taskbar*, fails to work. My monitor is fairly small, so I always maximize running programs. On Bookworm the only way to drag and drop files is to shrink both the sending and receiving programs and arrange them side-by-side to both be visible on the screen.

**Comment by spl237** [comment]
If a particular case isn't working, it will be an upstream Wayfire problem and not something we have changed - I suggest therefore that you report it at https://github.com/WayfireWM/wayfire.

In the case of the taskbar not supporting drag-and-drop, I'd suggest reporting at https://github.com/WayfireWM/wf-shell, as the task switcher is taken directly from there.

**Comment by Botspot** [comment]
ok

**Comment by Botspot** [comment]
Issue opened here: https://github.com/WayfireWM/wf-shell/issues/202
