### ISSUE TITLE
Please pull in a recent Wayfire patch so that Waydroid can work

### ISSUE THREAD

**Issue by Botspot** [raspberrypi-ui/wayfire#7]
Upstream Wayfire recently got a patch that fixes this problem:

> Add subsurfaces to the back that are meant to be below the parent surface
> Most applications add their subsurfaces above the parent, so we were blindly adding them to the front. This patch checks if the subsurface should be below, and adds it to the back in that case, or else adds it to the front.

One of these programs is Waydroid - an Android emulator. The PR with the patch is here: https://github.com/WayfireWM/wayfire/pull/2099
Would the team here be willing to pull in this patch to the RPi fork of Wayfire so that we can get more software running out of the box?

**Comment by spl237** [comment]
As mentioned in https://github.com/raspberrypi-ui/wayfire/issues/8, there have been significant changes to the architecture of wayfire between version 0.7 as used on RPiOs and upstream.

The area of the code to which this patch applies does not even exist in 0.7, so it is not possible to pull it in to our version. As and when we update to a newer version, this will come in anyway.
