### ISSUE TITLE
New wayfire update crashes when closing most programs using the panel

### ISSUE THREAD

**Issue by Botspot** [raspberrypi-ui/wayfire#9]
This might just be an edge case I am encountering, but ever since the most recent wayfire update to `0.7.5-1~bpo11+1~rpt32`, it has crashed repeatedly.
Seems like opening Text Editor (mousepad) and most other programs, then right-clicking on the taskbar icon and clicking Close will crash the desktop session and throw me back to the login screen.

Desktop processes that were running before are now gone, but in the task manager I can still see them.
So far today I have accidentally closed programs using the taskbar and crashed the desktop 11 times, so there are lots of groups of 11 identical process names in Task Manager. Hopefully someone can reproduce this and fix it, especially if this issue is affecting everybody?

OS details: PiOS 64-bit Bookworm with Wayland enabled, fully up to date, RPi5, no notable system changes that I am aware of.

**Comment by ghollingworth** [comment]
Yeah I can reproduce that as well, I'm guessing this is related to a recent change in the handling of events in the panel...

**Comment by Botspot** [comment]
Thank you for confirming. It pains me to think about all the users losing unsaved work when the desktop crashes. Hopefully it is a quick fix.
I will note - copy and paste through sandboxed Xwayland apps now works, so this wayfire update was not completely bad.

**Comment by spl237** [comment]
Repeated here. Problem identified and fixed. Will push an update later today.

**Comment by spl237** [comment]
Fix uploaded to apt - should be available later on today in version ...rpt33 of wayfire. Please re-open if this doesn't fix the problem.

**Comment by Botspot** [comment]
> Fix uploaded to apt - should be available later on today in version ...rpt33 of wayfire.

It has been 18 hours and still nothing new in apt update. Is that to be expected?

**Comment by Botspot** [comment]
Problem still occurs. Wayfire update has still not made it to apt.

> Please re-open if this doesn't fix the problem.

Github is not allowing me to re-open.

**Comment by spl237** [comment]
There is no need to reopen the issue if you are just waiting for the fix to be uploaded to apt. Please have some patience.

**Comment by Botspot** [comment]
> Please have some patience.

Sorry, I'm used to development that happens at the speed of thought.
Keep needing to be reminded that most things move slower than that.
